### ISSUE TITLE
removeView(…) not work

### ISSUE THREAD

**Issue by Horst1234** [homayoonahmadi/GroupBoxLayout#1]
The function removeView(…) has no effect.

**Comment by homayoonahmadi** [comment]
Hi there, Can you explain more about the issue or provide some code so I can reproduce the situation and fix the problem?

**Comment by Horst1234** [comment]
layout:

...
&lt;LinearLayout
&nbsp;&nbsp;&nbsp;&nbsp;android:id="@+id/linearLayout"
&nbsp;&nbsp;&nbsp;&nbsp;style="@style/layoutStyleSettingEntry"
&nbsp;&nbsp;&nbsp;&nbsp;android:orientation="horizontal"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;TextView
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;android:id="@+id/linearLayoutText"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;android:layout_width="wrap_content"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;android:layout_height="wrap_content"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;android:text="Hello&nbsp;World!"&nbsp;/&gt;
&lt;/LinearLayout&gt;

&lt;ir.programmerplus.groupbox.GroupBoxLayout
&nbsp;&nbsp;&nbsp;&nbsp;android:id="@+id/groupBoxLayout"
&nbsp;&nbsp;&nbsp;&nbsp;android:layout_width="match_parent"
&nbsp;&nbsp;&nbsp;&nbsp;android:layout_height="wrap_content"
&nbsp;&nbsp;&nbsp;&nbsp;android:layout_margin="5dp"
&nbsp;&nbsp;&nbsp;&nbsp;android:layoutDirection="ltr"
&nbsp;&nbsp;&nbsp;&nbsp;android:padding="30dp"
&nbsp;&nbsp;&nbsp;&nbsp;app:borderCornerRadius="8dp"
&nbsp;&nbsp;&nbsp;&nbsp;app:borderStrokeWidth="2.2dp"
&nbsp;&nbsp;&nbsp;&nbsp;app:labelText="Form&nbsp;Title"
&nbsp;&nbsp;&nbsp;&nbsp;app:labelTextSize="15dp"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;TextView
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;android:id="@+id/groupBoxLayoutText"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;android:layout_width="wrap_content"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;android:layout_height="wrap_content"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;android:text="Hello&nbsp;World!"&nbsp;/&gt;
&lt;/ir.programmerplus.groupbox.GroupBoxLayout&gt;
...

---

code:
LinearLayout linearLayout = (LinearLayout) findViewById(R.id.linearLayout);
//works
linearLayout.removeView(linearLayout.findViewById(R.id.linearLayoutText));

GroupBoxLayout groupBoxLayout = (GroupBoxLayout) findViewById(R.id.groupBoxLayout);
//no effect
groupBoxLayout.removeView(linearLayout.findViewById(R.id.groupBoxLayoutText));

**Comment by homayoonahmadi** [comment]
The bug has fixed (version 1.2.0) and `removeView` function now works as expected. Thank you for your participation.

**Comment by Horst1234** [comment]
I referenced the new version:

implementation 'com.github.homayoonahmadi:GroupBoxLayout:1.2.0'

... but  removeView(...) still has no effect.

**Comment by homayoonahmadi** [comment]
In your code you provided in previous comment there is a mistake,

this line :
`groupBoxLayout.removeView(linearLayout.findViewById(R.id.groupBoxLayoutText));`

should be like this:
`groupBoxLayout.removeView(groupBoxLayout.findViewById(R.id.groupBoxLayoutText));`

I have tested code and it works as expected. you can try example project or provide your code so I can check if there is something wrong in your code.

**Comment by Horst1234** [comment]
Oh yeah that was a mistake. Thanks.
