### ISSUE TITLE
What is the license for using GroupBoxLayout?

### ISSUE THREAD

**Issue by fusisan** [homayoonahmadi/GroupBoxLayout#3]
Hi,
Could you please specify the license you intend for this project? It would be great to know if it's under an open-source license like MIT, Apache, or GPL, for instance. 

Thanks!

**Comment by homayoonahmadi** [comment]
Hi @fusisan,
I'm going to use MIT as the license of this project. Please feel free to use it in your projects!

**Comment by fusisan** [comment]
Okay,
Thank you!!
